package io.conekta.compose.resources

/**
 * Card brand icon resources
 * 
 * Note: These are resource IDs that will be generated by Android's R class
 * The actual drawables are in src/androidMain/res/drawable/
 */
object CardBrandIcons {
    // These will be resolved at runtime by Android's resource system
    const val VISA = "ic_visa_card"
    const val MASTERCARD = "ic_mastercard_card"
    const val AMEX = "ic_amex_card"
    const val CONEKTA_LOGO = "ic_conekta_logo"
}

